### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-cise#11]
According to @canbax When there are no clusters or just a small one, the performance is laggy.
See https://github.com/ugurdogrusoz/visuall/issues/308.

**Comment by ugurdogrusoz** [comment]
Related to [this](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/issues/22)?

**Comment by canbax** [comment]
I think this problem is not related to layout-utilities. I made a performance test and I see the below image
![image](https://user-images.githubusercontent.com/8426741/103199309-a3618300-48fb-11eb-98db-03563508986c.png)

You can see that `calcRepulsionForces`takes too much time here, not the layout-utilities. I also attached the Performance Test file
[Profile-20201228T105931.json.zip](https://github.com/iVis-at-Bilkent/cytoscape.js-cise/files/5746342/Profile-20201228T105931.json.zip)

**Comment by ugurdogrusoz** [comment]
Looks like the major problem with performance is due to not using the FR grid variant used by other force-directed layout algorithms we have like CoSE. Let's implement FR grid variant.

Let's also make sure repulsion forces are not redundantly (twice) calculated for in-circle nodes as we noticed.

**Comment by herencalik** [comment]
I fixed the in-circle node repulsion force calculation problem but because we developed the expanding circle model based on their moves, as it is approximately halved now, I decreased the escape limit to expand the circle,  too. I tested the layouts, however, I'm not sure about the quality. @ugurdogrusoz hocam, could you check the quality?

**Comment by ugurdogrusoz** [comment]
Looks reasonable @herencalik. Let's evaluate more carefully after FR grid variant is implemented.

**Comment by ugurdogrusoz** [comment]
@canbax The performance should be improved now.

**Comment by canbax** [comment]
I see an improvement but I still see a lag around 900-1000 ms. It is not too bad. It just makes a small freezing in the browser. This lag is around 50-100 ms in fcose.

**Comment by ugurdogrusoz** [comment]
Can you please provide specific before & after numbers?

**Comment by canbax** [comment]
https://github.com/ugurdogrusoz/visuall/issues/308#issuecomment-735829171 here I see it was around 1400-1500 ms. Now it is around 1000 ms.

**Comment by ugurdogrusoz** [comment]
Let's sleep on this for a while and see the performance as is.
